const SUPABASE_URL = "https://kckxavutjoenznsvqnqt.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtja3hhdnV0am9lbnpuc3ZxbnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU3MDEzNjksImV4cCI6MjEwMTI3NzM2OX0.BOMHhPC0piS3Vixymb2BRezKpzCsA37lUdjXvfAvjnY";
